### ISSUE TITLE
.Permalink subject option not working

### ISSUE THREAD

**Issue by pimoore** [svendahlstrand/plugin-reply-by-email#3]
Love this new functionality, Sven!  The only subject option that’s not working is the .Permalink option (only shows Reply to: and then is blank), which I tested on an image-only test post.  I can’t figure out for the life of me why it doesn’t work.  When I used it in Tufte I added the safeURL function to the permalink, but that made no difference for this.

**Comment by svendahlstrand** [comment]
Oh, nice find, thanks for the report. 😊 I will add extra safeguarding for media-only posts.

**Comment by pimoore** [comment]
Thanks Sven, this worked perfectly! 🙏
